export const COUNTRIES: { [key: string]: string } = {
  US: "United States",
  GB: "England",
  FR: "France",
  DE: "Germany",
  IT: "Italy",
  CN: "China",
  JP: "Japan",
  KR: "South Korea",
  RU: "Russia",
  CA: "Canada",

  AT: "Austria",
  BE: "Belgium",
  BG: "Bulgaria",
  HR: "Croatia",
  CZ: "Czech Republic",
  DK: "Denmark",
  FI: "Finland",
  GR: "Greece",
  HK: "Hong Kong",
  HU: "Hungary",
  IE: "Ireland",
  IL: "Israel",
  NL: "Netherlands",
  NO: "Norway",
  PL: "Poland",
  PT: "Portugal",
  RO: "Romania",
  RS: "Serbia",
  ES: "Spain",
  SE: "Sweden",
  TR: "Turkey",
  UA: "Ukraine",

  AU: "Australia",
  AR: "Argentina",
  BR: "Brazil",
  CL: "Chile",
  CO: "Colombia",
  IS: "Iceland",
  MX: "Mexico",
  NZ: "New Zealand",
  VE: "Venezuela",

  AZ: "Azerbaijan",
  EG: "Egypt",
  IN: "India",
  ID: "Indonesia",
  KZ: "Kazakhstan",
  MY: "Malaysia",
  NG: "Nigeria",
  PK: "Pakistan",
  PH: "Philippines",
  SA: "Saudi Arabia",
  ZA: "South Africa",
  SU: "Soviet Union",
  TH: "Thailand",
  VN: "Vietnam",
};

export const LANGUAGES: { [key: string]: string } = {
  en: "English",
  es: "Spanish",

  fr: "French",
  de: "German",
  it: "Italian",
  cn: "Mandarin",
  zh: "Chinese",
  ja: "Japanese",
  ko: "Korean",
  ru: "Russian",

  sq: "Albanian",
  bg: "Bulgarian",
  hr: "Croatian",
  cs: "Czech",
  da: "Danish",
  nl: "Dutch",
  et: "Estonian",
  fi: "Finnish",
  ka: "Georgian",
  el: "Greek",
  he: "Hebrew",
  hu: "Hungarian",
  is: "Icelandic",
  lv: "Latvian",
  lt: "Lithuanian",
  no: "Norwegian",
  pl: "Polish",
  pt: "Portuguese",
  ro: "Romanian",
  sr: "Serbian",
  sv: "Swedish",
  tr: "Turkish",
  uk: "Ukrainian",

  af: "African",
  ar: "Arabic",
  az: "Azerbaijani",
  bn: "Bengali",
  fa: "Persian",
  hi: "Hindi",
  id: "Indonesian",
  kk: "Kazakh",
  mk: "Macedonian",
  ms: "Malay",
  sw: "Swahili",
  ta: "Tamil",
  te: "Telugu",
  th: "Thai",
  tl: "Tagalog",
  ur: "Urdu",
  vi: "Vietnamese",
};
